name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: "main" 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add repo
      uses: actions/checkout@v1
    - name: start script
      run: |
        chmod +x script.sh
        ./script.sh
      
